# Generated by Django 3.0.8 on 2020-07-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkordbase.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('votes_sum', models.PositiveIntegerField(default=0)),
                ('bpm', models.PositiveSmallIntegerField(default=110)),
                ('music_data', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkordbase.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pick_vote', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('votes_up', models.PositiveIntegerField(default=0)),
                ('votes_down', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkordbase.Pick')),
            ],
        ),
    ]
