# Generated by Django 3.0.8 on 2020-08-02 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            managers=[
                ('qs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('location', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_songs', to='akkordbase.Profile')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='akkordbase.Artist')),
            ],
            managers=[
                ('qs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tracklist',
            field=models.ManyToManyField(related_name='performers', to='akkordbase.Song'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('votes_sum', models.PositiveIntegerField(default=0)),
                ('bpm', models.PositiveSmallIntegerField(default=110)),
                ('music_data', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='akkordbase.Profile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='akkordbase.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pick_vote', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('votes_up', models.PositiveIntegerField(default=0)),
                ('votes_down', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkordbase.Pick')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_artists', to='akkordbase.Profile'),
        ),
    ]
