# Generated by Django 3.0.8 on 2020-08-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akkordbase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='author',
            new_name='added_by',
        ),
    ]
