# Generated by Django 3.0.8 on 2020-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkordbase', '0002_auto_20200802_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.TextField()),
                ('cycle_length', models.PositiveSmallIntegerField(default=4)),
            ],
        ),
    ]
