# Generated by Django 3.0.8 on 2020-07-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkordbase', '0002_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
