# Generated by Django 3.0.8 on 2020-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkordbase', '0004_auto_20200728_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
