# Generated by Django 3.0.8 on 2020-07-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akkordbase', '0005_auto_20200728_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pick',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='akkordbase.Song'),
        ),
    ]
