# Generated by Django 3.0.8 on 2020-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkordbase', '0006_auto_20200728_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='pick_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
