# Generated by Django 3.0.8 on 2020-07-30 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akkordbase', '0007_auto_20200728_1412'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='artist',
            managers=[
                ('qs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('qs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('tracklist', models.ManyToManyField(related_name='performers', to='akkordbase.Song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
